########################## File Info ###########################################
### Author: Benjamin Juarez
### Date: 07/03/2020
### Last Update: 9/15/20
### Desc: Builds and cleans datasets, synthethically generates training data, 
###       and implements Random Forest modeling for analysis of 2019 Bolivian
###       Presidential Election

########################## Libraries ###########################################

library(MASS)
library(truncnorm)
library(stringr)
library(randomForest)
library(dummies)
library(grid)
library(gridExtra)
library(xtable)
library(caret)
library(tidyverse)
library(classInt)
library(ggplot2)
library(nlme)
library(merTools)
library(imputeTS)
library(caTools)
library(msm)

########################## Construct Master Data Set ###########################

### read in computo (official) data
setwd("/Users/benjuarez/Desktop/SURF/Training_Data") 
results2019 <- read.csv(file = "results2019.csv", header = TRUE) %>%
  na_replace(., 0) # replaces blanks with 0s
  
results2019 <- rename(results2019, c("MUNICIPALITY" = "MUNICPALITY")) %>%
  rename(c("ELECTORATE" = "ELECTORATES")) # fixes minor spelling errors

for (i in 1:nrow(results2019)) # loops through each mesa
{
  valid_votes <- results2019$MAS[i] + results2019$CC[i] + results2019$X21F[i] +
    results2019$PDC[i] + results2019$MTS[i] + results2019$UCS[i] + 
    results2019$FPV[i] + results2019$MNR[i] + results2019$PAN.BOL[i]
  # confirms that valid vote totals are accurate
  if (results2019$VALID[i] != valid_votes) 
  {
    results2019$VALID[i] <- valid_votes
  }
  
  total_votes <- valid_votes + results2019$BLANK[i] + results2019$NULL.[i]
  # confirms that total votes are accurate
  if (results2019$VOTES[i] != total_votes) 
  {
    results2019$VOTES[i] <- total_votes
  }
  
  # creates columns for MAS vote shares and turnout for each mesa
  results2019$MAS.vote[i] <- round(results2019$MAS[i] / (results2019$VALID[i]), digits = 3)
  results2019$Turnout[i] <- round(results2019$VOTES[i] / results2019$ELECTORATE[i], digits = 3)
  
}
# filters out mesas with appropriate turnout and valid votes
results2019 <- filter(results2019, VALID > 150) #%>%
  #filter(Turnout != 0)
           
### read in past election data, demographic data 
setwd("/Users/benjuarez/Desktop/SURF/Training_Data") # sets working directory
# demographic data from https://www.citypopulation.de/Bolivia.html 
# (2012 Census data)
demographics <- read.csv(file = "demographics.csv", header = TRUE, sep=",")
demographics[45, 4] <- 13820
demographics$MUNICIPALITY <- str_replace(string = demographics$MUNICIPALITY, 
                                         pattern = "Independencia", 
                                         replacement = 
                                           "Ayopaya (Villa de Independencia)")
# 2014 election data from OEP
dep_results2014 <- read.csv(file = "dep_results2014.csv", header = TRUE, sep=",")
data2014 <- data.frame()# blank data frame

for (i in 1:63) # loop through each circunscripcion (district) number
{
  # Filter demographic data by circunscripcion number
  districts <- filter(demographics, DISTRICT == i)
  
  # Generate appropriate for each circunscripcion
  male_pop <- sum(districts[, "MALE_POP"])
  female_pop <- sum(districts[, "FEMALE_POP"])
  age_0_14 <- sum(districts[, "AGE_0_14"])
  age_65 <- sum(districts[, "AGE_65"])
  literate <- sum(districts[, "LITERATE"])
  rural <- sum(districts[, "RURAL"])
  population <- sum(districts[, "POPULATION"])
  
  # Generate values to be added to vote data
  p.14.younger <- round(age_0_14 / population, 3)
  p.65.older <- round(age_65 / population, 3)
  p.literate <- round(literate / (population - age_0_14), 3)
  p.rural <- round(rural / population, 3)
  p.male <- round(male_pop / population, 3)
  
  # Add demographic data to appropriate section in 2014 results data
  votes2014 <- dplyr::filter(dep_results2014, DISTRICT == i)
  
  votes2014["P.14.YOUNGER"] <- p.14.younger
  votes2014["P.65.OLDER"] <- p.65.older
  votes2014["P.LITERATE"] <- p.literate
  votes2014["P.RURAL"] <- p.rural
  votes2014["P.MALE"] <- p.male
  
  # combined historical and demographic data
  data2014 <- rbind(data2014, votes2014)
}
data2014 <- rename(data2014, c("ELECTORATE" = "ELECTORATES"))

########################## Generate Clean Simulated Data #######################

# model for turnout generated by linear mixed regression
mlr.turnout <- lmer(P.TURNOUT ~  P.RURAL + P.MAS.VOTE + P.MALE + P.LITERATE + 
                    P.14.YOUNGER + P.65.OLDER + P.NULL + P.BLANK + 
                    (1|DEPARTMENT), data = data2014)
# records fitted values, upper\lower bounds for turnout at circunscripcion level
intervals.turnout <- as.data.frame(predictInterval(mlr.turnout, stat = "mean"))

# model for MAS vote generated by linear mixed regression
mlr.mas.vote <- lmer(P.MAS.VOTE ~  P.RURAL + P.TURNOUT + P.MALE + P.LITERATE + 
                       P.14.YOUNGER + P.65.OLDER + P.NULL + P.BLANK + 
                       (1|DEPARTMENT), data = data2014)
# records fitted values, upper\lower bounds for MAS vote at circunscripcion level
intervals.mas.vote <- as.data.frame(predictInterval(mlr.mas.vote, 
                                                    stat = "mean"))

# template for training data
clean_data <- data.frame(District = numeric(), Turnout = numeric(), 
                        MAS.vote = numeric(), Mesa = numeric())

# 2014 department data for mesas and electorates
dep_data <- data.frame(DEPARTMENT = c("chuquisaca", "la_paz", "cochabamba", 
                                      "oruro", "potosi", "tarija", "santa_cruz",
                                      "beni", "pando"), MESAS = c(1828, 8988, 
                                      6134, 1646, 2338, 1802, 8621, 1302, 389), 
                                      ELECTORATE = c(323129, 1678769, 1128351,
                                      293576, 409144, 323351, 1533638, 223598,
                                      57596)) 

# adds number of mesas within each circunscripcion proportional to its electorate
for (i in 1:5)
{
  data2014$MESAS[i] <- (data2014$ELECTORATE[i] / dep_data[1,3]) * dep_data[1,2]
}
for (i in 6:19)
{
  data2014$MESAS[i] <- (data2014$ELECTORATE[i] / dep_data[2,3]) * dep_data[2,2]
}
for (i in 20:28)
{
  data2014$MESAS[i] <- (data2014$ELECTORATE[i] / dep_data[3,3]) * dep_data[3,2]
}
for (i in 29:32)
{
  data2014$MESAS[i] <- (data2014$ELECTORATE[i] / dep_data[4,3]) * dep_data[4,2]
}
for (i in 33:39)
{
  data2014$MESAS[i] <- (data2014$ELECTORATE[i] / dep_data[5,3]) * dep_data[5,2]
}
for (i in 40:43)
{
  data2014$MESAS[i] <- (data2014$ELECTORATE[i] / dep_data[6,3]) * dep_data[6,2]
}
for (i in 44:57)
{
  data2014$MESAS[i] <- (data2014$ELECTORATE[i] / dep_data[7,3]) * dep_data[7,2]
}
for (i in 58:61)
{
  data2014$MESAS[i] <- (data2014$ELECTORATE[i] / dep_data[8,3]) * dep_data[8,2]
}
for (i in 62:63)
{
  data2014$MESAS[i] <- (data2014$ELECTORATE[i] / dep_data[9,3]) * dep_data[9,2]
}
# cleans up values
data2014$MESAS <- as.numeric(data2014$MESAS) 
data2014$MESAS <- round(data2014$MESAS)

a <- 1
for (i in 1:63) # loops through each circunscripcion
{
  for (x in 1:as.numeric(data2014$MESAS[i]))
  {
    # predicts turnout and MAS vote for appropriate number of mesas within 
    # each circunscripcion
    to_add <- list(District = i, Turnout = rtnorm(n = 1, 
                                                  mean=intervals.turnout[i,1], 
                                                  lower=intervals.turnout[i,3], 
                                                  upper=intervals.turnout[i,2]), 
                   MAS.vote = rtnorm(n = 1, mean=intervals.mas.vote[i,1], 
                                     lower=intervals.mas.vote[i,3], 
                                     upper=intervals.mas.vote[i,2]), Mesa = a)
    clean_data <- rbind(clean_data, to_add)
    a <- a + 1
  }
}

# adds Department data to corresponding districts
to_add <- data.frame(Department=data2014$DEPARTMENT, District=data2014$DISTRICT)
clean_data <- left_join(clean_data, to_add, by="District")
clean_data <- clean_data[, c(4, 5, 1, 2, 3)]

########################## Generate Manipulated Simulated Data #################

# parameters for determining proportion, extent, etc. of fraud for simulation
base.vs.prop <- 1/4
base.bbs.prop <- 1/4
vs.coef <-  4/5
bbs.coef <- 5/6
stolen.var <- 0.0025
bboxstuff.var <- 0.005
stolen.bboxstuff.cov <- 0
Sigma <- matrix(c(stolen.var, stolen.bboxstuff.cov, 
                  stolen.bboxstuff.cov, bboxstuff.var ), 2, 2)
# ensures reproducible results
set.seed(100)

# randomly decides presence of fraud for each mesa with multinomial distribution
base_fraud <- t(rmultinom(nrow(clean_data), 1, 
                          c(base.vs.prop, base.bbs.prop, 
                            1- base.bbs.prop - base.vs.prop)))[, 1:2]
proportion_fraud <- as.data.frame(base_fraud * mvrnorm(n = nrow(clean_data), 
                                                       mu = c(vs.coef, bbs.coef),
                                                       Sigma = Sigma,
                                                       empirical = TRUE))
proportion_fraud[proportion_fraud < 0] <- 0 
proportion_fraud[proportion_fraud > 1] <- 1
proportion_fraud <- as.data.frame(proportion_fraud)
base_fraud <- as.data.frame(base_fraud)
# applies appropriate names
names(proportion_fraud) <- c("stolen.prop", "bboxstuff.prop")
names(base_fraud) <- c("VS", "BBS")
manip_data <- bind_cols(clean_data, base_fraud, proportion_fraud) 
# rounds accordingly
manip_data$stolen.prop <- round(manip_data$stolen.prop, digits = 3) 
manip_data$bboxstuff.prop <- round(manip_data$bboxstuff.prop, digits = 3)

# generates labeled simulated fraud data
for (i in 1:nrow(manip_data))
{
  # vote stealing (VS)
  if (manip_data$VS[i] == 1)
  {
    manip_data$MAS.vote[i] <- ((1 - manip_data$MAS.vote[i]) * 
                                 manip_data$stolen.prop[i]) + manip_data$MAS.vote[i]
    manip_data$Fraud.type[i] <- "VS"
  }
  # ballot box stuffing (BBS)
  else if (manip_data$BBS[i] == 1)
  {
    manip_data$Turnout[i] <- ((1 - manip_data$Turnout[i]) * manip_data$bboxstuff.prop[i]) +
                                 manip_data$Turnout[i]
    manip_data$Fraud.type[i] <- "BBS"
  }
  # clean
  else
  {
    manip_data$Fraud.type[i] <- "Clean"
  }
}

########################## Random Forest Modeling ##############################

### randomly generate training and validation sets in order to check accuracy
set.seed(50) 
sample <- sample(1:nrow(manip_data), 0.9*nrow(manip_data), replace = FALSE) 
train <- manip_data[sample,]
train <- train[c("Department", "Turnout", "MAS.vote", 
             "Fraud.type")]
train$Fraud.type <- factor(train$Fraud.type)
validate <- manip_data[-sample,]
validate_data <- validate[c("Department", "Turnout", "MAS.vote")]
validate_fraud_type <- validate[c("Fraud.type")]
validate_fraud_type <- factor(validate_fraud_type$Fraud.type)

### train the model with portion of synthetic data
rf_model_1 <- randomForest(Fraud.type ~ ., ntree=400, mtry=1, data=train, 
                         importance=TRUE)

### check accuracy of model with validation set from synthetic data
validate_pred <- predict(rf_model, validate_data)
rf_accuracy <- round(100*mean(validate_pred == validate_fraud_type), digits = 2)
accuracy_table <- xtable(table("Predictions"=validate_pred, 
                               "Fraud Type"=validate_fraud_type, 
                               dnn=c("Actual","Predictions")))


### prepare data for further implementation
training_data <- manip_data[c("Department", "Turnout", "MAS.vote", 
                              "Fraud.type")]
testing_data <- results2019[c("DEPARTMENT", "MUNICIPALITY", "PRECINCT", 
                              "Turnout", "MAS.vote")] %>%
  rename(Department = DEPARTMENT, Municipality = MUNICIPALITY, 
         Precinct = PRECINCT)
training_data$Fraud.type <- factor(training_data$Fraud.type)

### train the model on full training data
set.seed(75)
rf_model_2 <- randomForest(Fraud.type ~ ., ntree=400, mtry=1, data=training_data, 
                         importance=TRUE)
varImpPlot(rf_model_2, main="Importance of Predictors in Model")

### Use the model to predict fraud classifications in real data
predictions <- predict(rf_model_2, testing_data)
rf_results <- testing_data
rf_results$Fraud.type <- predictions
table(rf_results$Fraud.type)

########################## Figures to Output ###################################

# figures for turnout and vote share of clean/manipulated data
manip_turnout <- hist(manip_data$Turnout, 
                      main="Manipulated Synthetic Data Turnout", 
                      xlab="Turnout", 
                      border="black", 
                      col="royal blue",
                      xlim=c(.80,1.0),
                      ylim=c(0,4500))
manip_voteshare <- hist(manip_data$MAS.vote, 
                        main="Manipulated Synthetic Data MAS Vote Share", 
                        xlab="MAS Vote Share", 
                        border="black", 
                        col="royal blue",
                        xlim=c(.20,1.0),
                        ylim=c(0,4500))

clean_turnout <- hist(clean_data$Turnout, 
                      main="Clean Synthetic Data Turnout", 
                      xlab="Turnout", 
                      border="black", 
                      col="royal blue",
                      xlim=c(.80,1.0),
                      ylim=c(0,4500))
clean_voteshare <- hist(clean_data$MAS.vote, 
                        main="Clean Synthetic Data MAS Vote Share", 
                        xlab="MAS Vote Share", 
                        border="black", 
                        col="royal blue",
                        xlim=c(.20,1.0),
                        ylim=c(0,4500))

# distributions within manipulated, synthetic data

# clean <- filter(manip_data, Fraud.type=="Clean")
# clean_turnout <- hist(clean$Turnout, 
#                       main="Turnout in Clean Mesas", 
#                       xlab="Turnout", 
#                       border="black", 
#                       col="grey",
#                       xlim=c(.80,1.0),
#                       ylim=c(0,3000))
# clean_voteshare <- hist(clean$MAS.vote, 
#                         main="MAS Vote Share in Clean Mesas", 
#                         xlab="MAS vote", 
#                         border="black", 
#                         col="grey")

BBS <- filter(manip_data, Fraud.type=="BBS")
BBS_turnout <- hist(BBS$Turnout, 
                    main="Turnout in Mesas Affected by BBS", 
                    xlab="Turnout", 
                    border="black", 
                    col="red",
                    xlim=c(.80,1.0),
                    ylim=c(0,2000))
BBS_voteshare <- hist(BBS$MAS.vote, 
                   main="MAS Vote Share in Mesas Affected by BBS", 
                   xlab="MAS Vote Share", 
                   border="black", 
                   col="red",
                   xlim=c(.10,1.0),
                   ylim=c(0,1500))

VS <- filter(manip_data, Fraud.type=="VS")
VS_turnout <- hist(VS$Turnout, 
                   main="Turnout in Mesas Affected by VS", 
                   xlab="Turnout", 
                   border="black", 
                   col="green",
                   xlim=c(.80,1.0),
                   ylim=c(0,2000))
VS_voteshare <- hist(VS$MAS.vote, 
                     main="MAS Vote Share in Mesas Affected by VS", 
                     xlab="MAS Vote Share", 
                     border="black", 
                     col="green",
                     xlim=c(.10,1.0),
                     ylim=c(0,1500))


# synthetic data statistics

# FIGURE #
# importance of predictors in random forest model
var_importance <- varImpPlot(rf_model_2, main="Importance of Predictors in Model")


# TABLE #
# Table that shows accuracy of random forest model
accuracy_table <- xtable(table("Predictions"=validate_pred, 
                               "Fraud Type"=validate_fraud_type, 
                               dnn=c("Actual","Predictions")), 
                         label="Confusion Matrix")

rf_accuracy <- round(100*mean(validate_pred == validate_fraud_type), digits = 2)

# TABLE #
# percentage of clean and at risk mesas in real data
frequencies <- as.data.frame(table(rf_results$Fraud.type))
p.clean <- round(frequencies[2,2] / sum(frequencies[,2]), digits = 3) * 100
p.bbs <- round(frequencies[1,2] / sum(frequencies[,2]), digits = 3) * 100
p.vs <- round(frequencies[3,2] / sum(frequencies[,2]), digits = 3) * 100
p.fraud <- round((frequencies[1,2] + frequencies[3,2]) / sum(frequencies[,2]), 
                 digits = 3) * 100
p.turnout <- round(mean(rf_results$Turnout), digits = 2)
p.MAS.vote <- round(mean(rf_results$MAS.vote), digits = 2)
# outputs table with summary statistics for all mesas
all_mesas_table <- xtable(data.frame("Clean"=p.clean, "At Risk"=p.fraud, 
                                     "BBS Risk"=p.bbs, "VS Risk"=p.vs, 
                                     "Avg Turnout"=p.turnout, 
                                     "Avg MAS vote"=p.MAS.vote, 
                                     row.names = c("All Mesas")), 
                     caption="This table displays the predictions from the 
                     Random Forest model.", label="LaTeX")

# TABLE
# breakdowns within each department
departments <- data.frame(Department= c("Chuquisaca", "La Paz", "Cochabamba", 
                                        "Oruro", "Potosí", "Tarija", 
                                        "Santa Cruz", "Beni", "Pando"))
for (i in 1:9)
{
  dep_table_name <- paste("table", departments[i, 1], sep=".")
  rownames <- paste(departments[i, 1], "Mesas", sep=" ")

  results <- filter(rf_results, Department %in% departments[i, 1])
  frequencies <- as.data.frame(table(results$Fraud.type))
  # clean/at-risk variables generated for each department
  p.clean <- round(frequencies[2,2] / sum(frequencies[,2]), digits = 3) * 100
  p.bbs <- round(frequencies[1,2] / sum(frequencies[,2]), digits = 3) * 100
  p.vs <- round(frequencies[3,2] / sum(frequencies[,2]), digits = 3) * 100
  p.fraud <- round((frequencies[1,2] + frequencies[3,2]) / sum(frequencies[,2]), 
                   digits = 3) * 100
  p.turnout <- round(mean(results$Turnout), digits = 2)
  p.MAS.vote <- round(mean(results$MAS.vote), digits = 2)
  
  dep_table <- data.frame("Clean"=p.clean, "At Risk"=p.fraud, 
                          "BBS Risk"=p.bbs, "VS Risk"=p.vs, 
                          "Avg Turnout"=p.turnout, 
                          "Avg MAS vote"=p.MAS.vote, row.names = rownames)
  dep_table <- xtable(dep_table)
  assign(dep_table_name, dep_table)
}
# generates table with departments as rows
dep_tables <- rbind(table.Chuquisaca, `table.La Paz`, table.Cochabamba, 
                    table.Oruro, table.Potosí, table.Tarija, `table.Santa Cruz`,
                    table.Beni, table.Pando)
dep_tables <- xtable(dep_tables, include.rownames = FALSE)
dep_tables <- dep_tables[order(dep_tables$Clean),]

# TABLE #
# breakdowns within at risk departments CHECK!!!!!!
at_risk <- data.frame(Department= c("La Paz", "Cochabamba", 
                                   "Potosí"))
demographics$DEPARTMENT <- str_replace_all(string = demographics$DEPARTMENT, 
                                           pattern = "La_Paz", 
                                           replacement = "La Paz") %>% 
  str_replace(pattern = "Potosi",replacement = "Potosí")
demographics$MUNICIPALITY <- str_replace_all(string = demographics$MUNICIPALITY,
                                             pattern = "_",
                                             replacement = " ") %>%
  str_replace(pattern = "Bulo Bulo",
              replacement = "Entre Ríos") %>%
  str_replace(pattern = "Tapacari",
              replacement = "Tapacarí") %>%
  str_replace_all(pattern = "San Pedro de Buena Vista",
                  replacement = "San Pedro") %>%
  str_replace_all(pattern = "Chimore",
                  replacement = "Chimoré") %>%
  str_replace_all(pattern = "Sica Sica",
                  replacement = "Sicasica") %>%
  str_replace_all(pattern = "Sipe Sipe",
                  replacement = "Sipesipe")
for (i in 1:3)
{
  # loops through each at-risk department
  results <- filter(rf_results, Department %in% at_risk[i, 1])
  dep_table_name <- paste("table", at_risk[i, 1], "deep", sep=".")
  muns <- as.data.frame(table(results$Municipality))
  colnames(muns) <- c("Municipality", "Mesas")
  mun_tables <- data.frame()

  for (x in 1:nrow(muns))
  {
    # loops through each municipality within each at-risk department
    mun_results <- filter(results, Municipality %in% muns[x, 1])
    mun_frequencies <- as.data.frame(table(mun_results$Fraud.type))
    # clean/at-risk variables
    p.clean <- round(mun_frequencies[2,2] / sum(mun_frequencies[,2]), digits = 3) * 100
    p.bbs <- round(mun_frequencies[1,2] / sum(mun_frequencies[,2]), digits = 3) * 100
    p.vs <- round(mun_frequencies[3,2] / sum(mun_frequencies[,2]), digits = 3) * 100
    p.fraud <- round((mun_frequencies[1,2] + mun_frequencies[3,2]) / sum(mun_frequencies[,2]), 
                     digits = 3) * 100
    p.turnout <- round(mean(mun_results$Turnout), digits = 2)
    p.MAS.vote <- round(mean(mun_results$MAS.vote), digits = 2)
 
    mun_table <- data.frame("Department"=at_risk[i,1], "Clean"=p.clean, 
                            "At Risk"=p.fraud, 
                            "BBS Risk"=p.bbs, 
                            "VS Risk"=p.vs, 
                            "Avg Turnout"=p.turnout, 
                            "Avg MAS vote"=p.MAS.vote, 
                            "Mesas"=muns[x,2],
                            row.names = muns[x, 1])
    
    mun_tables <- rbind(mun_tables, mun_table) %>%
      filter(Clean < 80) %>% # filters out clean municipalities
      filter (Mesas > 25) %>% # filters out municipalities with low # of mesas
      xtable()
    mun_tables <- mun_tables[order(mun_tables$Clean),]
  
  }
  assign(dep_table_name, mun_tables)
}

at_risk_muns <- data.frame()
at_risk_muns <- rbind(table.Potosí.deep, table.Cochabamba.deep, 
                      `table.La Paz.deep`)
at_risk_muns <- at_risk_muns[order(at_risk_muns$Clean),]

# TABLE #
# demographic data for at risk municipalities

dem_data <- demographics
mun_names <- row.names(at_risk_muns)
at_risk_dem_info <- data.frame()
for (i in 1:nrow(at_risk_muns))
{
  dem_info <- filter(dem_data, DEPARTMENT %in% at_risk_muns[i, 1]) %>%
    filter(MUNICIPALITY %in% mun_names[i])
  
  p.rural <- dem_info$P.RURAL[1]
  p.literate <- dem_info$P.LITERATE[1]
  
  dem_table <- data.frame("Department" = at_risk_muns[i,1], 
                          "Clean" = at_risk_muns[i,2],
                          "Rural" = p.rural,
                          "Literate" = p.literate,
                          "Mesas"= at_risk_muns[i,8])
  at_risk_dem_info <- rbind(at_risk_dem_info, dem_table)
}
row.names(at_risk_dem_info) <- mun_names
at_risk_dem_info <- at_risk_dem_info[order(at_risk_dem_info$Clean),]
at_risk_dem_info <- subset(at_risk_dem_info, select = -c(Clean))
at_risk_dem_info$Rural <- round(at_risk_dem_info$RURAL, digits = 2)
at_risk_dem_info$Literate <- round(at_risk_dem_info$LITERATE, digits = 2)

at_risk_muns <- subset(at_risk_muns, select = -c(Department))
rownames(at_risk_muns)[rownames(at_risk_muns) == "Ayopaya (Villa de Independencia)"] = "Ayopaya"
rownames(at_risk_dem_info)[rownames(at_risk_dem_info) == "Ayopaya (Villa de Independencia)"] = "Ayopaya"
at_risk_muns <- xtable(at_risk_muns)
at_risk_dem_info <- xtable(at_risk_dem_info)

# NAME
# Further analysis within municipalities

# NAME 
# map 
